import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: [
      "test/v17-kind-gate.test.ts",
      "test/token-program.test.ts",
      "test/encode.test.ts",
      "test/errors.test.ts",
      "test/instructions.test.ts",
      "test/pda.test.ts",
      "test/price-router.test.ts",
      "test/discovery.test.ts",      "test/slab-parser.test.ts",
      "test/adl.test.ts",
      "test/accounts.test.ts",
      "test/program-ids.test.ts",
      "test/stake.test.ts",
      "test/tx.test.ts",
      "src/solana/__tests__/stake.test.ts",
      "src/solana/__tests__/stake-cpi.test.ts",
      "test/integration-mocked.test.ts",
      "test/discovery-api-fallback.test.ts",
      "test/static-markets.test.ts",
      "test/discovery-static-fallback.test.ts",
      "test/discovery-fallback-integration.test.ts",
      "test/lighthouse.test.ts",
      "test/rpc-pool.test.ts",
      "test/drift-check.test.ts",
      "test/parity-fixtures.test.ts",
      "test/account-decode.test.ts",
      "test/parity/v12.17-encoder-bytes.parity.test.ts",
      "test/parity/v12.19-encoder-bytes.parity.test.ts",
      "test/vanilla.test.ts",
    ],
  },
});
